import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { promisify } from 'node:util';

const execute = promisify(execFile);
const generatedText =
  'Generated by a Raven workspace command.\nVerified through a local Git remote.\n';

function pdf() {
  const pages = ['Workspace PDF report', 'Second page verified'];
  const stream = (text) => {
    const command = `BT /F1 14 Tf 15 100 Td (${text}) Tj ET`;
    return `<< /Length ${Buffer.byteLength(command)} >>\nstream\n${command}\nendstream`;
  };
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R 5 0 R] /Count 2 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] /Contents 4 0 R /Resources << /Font << /F1 7 0 R >> >> >>',
    stream(pages[0]),
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] /Contents 6 0 R /Resources << /Font << /F1 7 0 R >> >> >>',
    stream(pages[1]),
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];
  let body = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(body));
    body += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xref = Buffer.byteLength(body);
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets
    .slice(1)
    .map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`)
    .join('')}`;
  return `${body}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
}

export async function createWorkspaceFixture(root) {
  const repository = join(root, 'attached workspace');
  const remote = join(root, 'artifact-remote.git');
  mkdirSync(repository);
  mkdirSync(remote);
  await execute('git', ['init', '-b', 'main'], { cwd: repository });
  await execute('git', ['config', 'user.name', 'Raven browser fixture'], { cwd: repository });
  await execute('git', ['config', 'user.email', 'browser@example.invalid'], { cwd: repository });
  await execute('git', ['init', '--bare', '-b', 'main'], { cwd: remote });
  await execute('git', ['remote', 'add', 'origin', remote], { cwd: repository });
  const run = async (options, executable, args) => {
    assert.equal(options.cwd, repository);
    assert.equal(options.permissionMode, 'bypassPermissions');
    const hook = options.hooks.PreToolUse[0].hooks[0];
    const id = crypto.randomUUID();
    const admission = await hook(
      {
        hook_event_name: 'PreToolUse',
        session_id: 'browser-workspace',
        cwd: repository,
        transcript_path: join(root, 'fake-transcript.jsonl'),
        tool_name: 'Bash',
        tool_input: { command: [executable, ...args].join(' ') },
        tool_use_id: id,
      },
      id,
      { signal: options.signal },
    );
    assert.notEqual(admission.hookSpecificOutput?.permissionDecision, 'deny');
    return execute(executable, args, { cwd: options.cwd });
  };
  return {
    repository,
    async generate(options) {
      const script = `const fs = require('node:fs');
        fs.mkdirSync('outputs', { recursive: true });
        fs.writeFileSync('outputs/report # українська.md', ${JSON.stringify(generatedText)});
        fs.writeFileSync('outputs/report.html', '<!doctype html><h1>Workspace HTML preview</h1><script>window.__artifactScriptRan=true; parent.__artifactEscape=true;</script>');
        fs.writeFileSync('outputs/chart.png', Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=', 'base64'));
        fs.writeFileSync('outputs/invalid.pdf', 'This is not a PDF');
        fs.writeFileSync('outputs/report.pdf', ${JSON.stringify(pdf())});`;
      await run(options, process.execPath, ['-e', script]);
      await run(options, 'git', ['add', 'outputs']);
      await run(options, 'git', ['commit', '-m', 'Generate browser workspace artifacts']);
      await run(options, 'git', ['push', 'origin', 'HEAD:main']);
    },
    async state() {
      try {
        const commit = await execute('git', ['rev-parse', 'main'], { cwd: remote });
        const artifact = await execute('git', ['show', 'main:outputs/report # українська.md'], {
          cwd: remote,
        });
        return { repository, commit: commit.stdout.trim(), artifact: artifact.stdout };
      } catch {
        return { repository };
      }
    },
  };
}
