export {
  defineAgent,
  defineSuite,
  buildPrompt,
  parseActions,
  parseMcpConfig,
  resolveEnvVars,
  type AgentDefinition,
  type ResolvedAgentDefinition,
  type SuiteManifest,
  type ResolvedSuiteManifest,
  type PromptParts,
  type ActionDefinition,
  type McpConfig,
} from './define.ts';

export {
  SUITE_ORCHESTRATOR,
  SUITE_TASK_MANAGEMENT,
  SUITE_EMAIL,
  SUITE_DAILY_BRIEFING,
  SUITE_NOTIFICATIONS,
  MCP_TICKTICK,
  MCP_GMAIL,
  AGENT_TICKTICK,
  AGENT_GMAIL,
  AGENT_DIGEST,
  AGENT_TELEGRAM,
  AGENT_ORCHESTRATOR,
  AGENT_PRODUCTIVITY_COORD,
  AGENT_COMMUNICATION_COORD,
  SUITE_GEMINI_TRANSCRIPTION,
  AGENT_GEMINI_TRANSCRIBER,
  SOURCE_GEMINI,
  SOURCE_GMAIL,
  SOURCE_TELEGRAM,
  SOURCE_ORCHESTRATOR,
  PROJECT_TELEGRAM_DEFAULT,
  SKILL_ORCHESTRATOR,
  EVENT_EMAIL_REPLY_START,
  EVENT_EMAIL_REPLY_SEND,
  EVENT_EMAIL_REPLY_EDIT,
  EVENT_EMAIL_REPLY_CANCEL,
  EVENT_EMAIL_TRIAGE_PROCESSED,
  EVENT_EMAIL_TRIAGE_ACTION_ITEMS,
} from './constants.ts';

export {
  MCP_NAMESPACE_SEP,
  MCP_TOOL_PATTERN_RE,
  MCP_TOOL_WILDCARD_RE,
  namespaceMcpKey,
  buildMcpToolPattern,
  buildLocalToNamespacedMap,
  rewriteAgentMcpRefs,
  validateAgentMcpRefs,
} from './mcp-naming.ts';
